{
 "title": "IOTproject",
 "time": { "from": "2022-09-08T16:23:49.000Z", "to": "2022-09-09T12:08:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "ZoneId",
    "label": "Area/Zone",
    "query": "SELECT ZoneId FROM SensorDevice"
   },
   {
    "name": "SensorId",
    "label": "Sensor",
    "query": "SELECT SensorId FROM SensorDevice  WHERE ZoneId = '$ZoneId'"
   }
  ]
 },
 "panels": [
  {
   "title": "Environment Monitor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Value_C AS \"temp (°C)\"\nFROM Temperature\nWHERE\n  SensorId = '$SensorId'\nORDER BY Timestamp;"
    },
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Value_perc AS \"mwc (%)\"\nFROM VolumetricWaterContent\nWHERE\n  SensorId = '$SensorId'\nORDER BY Timestamp;"
    },
    {
     "rawSql": "SELECT State\nFROM ActuatorDevice;"
    }
   ]
  },
  {
   "title": "Actuator STATE",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  State\nFROM ActuatorDevice\nWHERE ZoneId = '$ZoneId'\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Activation",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  AA.Timestamp as \"time\", count(AA.Timestamp) as \"session\"\nFROM ActuatorDevice as AD inner join ActuatorActivation as AA on AD.ActuatorId=AA.ActuatorId \nWHERE  ZoneId = '$ZoneId'\nGROUP BY AA.Timestamp, AD.ActuatorId\nORDER BY AA.Timestamp"
    }
   ]
  }
 ]
}